name: Lint on pull request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  full_ci:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      # Get the code into the container
      - name: Checkout
        uses: actions/checkout@v2
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Run install script
      - name: Install dependencies
        run: "scripts/install"
      # Lint the code
      - name: Lint code with black
        run: python3 -m black .
      # Test the code
      - name: Test code
        env:
          DETA_SDK_TEST_PROJECT_KEY: ${{secrets.DETA_SDK_TEST_PROJECT_KEY}}
          DETA_SDK_TEST_BASE_NAME: ${{secrets.DETA_SDK_TEST_BASE_NAME}}
        run: |
          python3 tests.py

      