name: Test release

on: 
  workflow_dispatch:

jobs:
  tag_and_release:
   runs-on: ubuntu-18.04
   steps:
    # Get the code into our container
    - name: Checkout
      uses: actions/checkout@v2
    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ^3.5
    # Install dependencies
    - name: Install dependencies
      run: "scripts/install"
    # Build package
    - name: Build package
      run: "scripts/build"
    # Make tag
    - name: Make git tag
      run: "scripts/tag"
     # Create Github release
    - name: Create release
      run: "scripts/release"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Publish with twine
    - name: Publish with twine
      run: "scripts/test_publish"
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    